source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ‘8.0’
inhibit_all_warnings!

xcodeproj 'TutorialScrollViewController'
use_frameworks!

target 'TutorialScrollViewController_Example' do
  pod 'TutorialScrollViewController', :path => '../'  
end
