source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TutorialScrollViewController_Example', :exclusive => true do
  pod 'TutorialScrollViewController', :path => '../'
end

target 'TutorialScrollViewController_Tests', :exclusive => true do
  pod 'TutorialScrollViewController', :path => '../'

  
end
